name: BudgetMint
options:
  bundleIdPrefix: com.brucebishop
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  plaid-link-ios:
    url: https://github.com/plaid/plaid-link-ios
    from: "5.0.0"

targets:
  BudgetMint:
    type: application
    platform: iOS
    sources:
      - BudgetMint
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseCore
      - package: firebase-ios-sdk
        product: FirebaseAuth
      - package: firebase-ios-sdk
        product: FirebaseFirestore
      - package: firebase-ios-sdk
        product: FirebaseFunctions
      - package: plaid-link-ios
        product: LinkKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.brucebishop.BudgetMint
      INFOPLIST_GENERATION_CLASS: $(PRODUCT_MODULE_NAME).BudgetMintApp
      GENERATE_INFOPLIST_FILE: true
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: 1
      SWIFT_EMIT_LOC_STRINGS: true
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
